### ISSUE TITLE
Reserved Keywords

### ISSUE THREAD

**Issue by guilhermecgs** [tyarkoni/transitions#152] opened 2016-10-19 14:50 UTC
Hi,

Is "firstSegment", "secondSegment" and "thirdSegment"  reserved keywords?

Every time I try to create a state-machine with a state named "firstSegment" it gives me an error

pseudoCode:

```
{'name': 'master', 'children': ['firstSegment', 'segment2', 'segment3', 'finalSegment']}

self.machine = Machine(model=self, states=self.states, transitions=self.transitions, auto_transitions=False, ignore_invalid_triggers=True, initial='myInitialState')

self.graph.draw('my_state_diagram88.png', prog='dot')

```

 self.graph.draw('my_state_diagram88.png', prog='dot')
  File "C:\Anaconda2_x64\lib\site-packages\pygraphviz\agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "C:\Anaconda2_x64\lib\site-packages\pygraphviz\agraph.py", line 1335, in _run_prog
    raise IOError(b"".join(errors))
IOError

**Comment by aleneum** [comment] 2016-10-19 16:19
Hi @guilhermecgs,

that looks like an issue with pygraphviz. Unfortunately, the pygraphviz error output is (ironically) kind of bugged (b"".join(error) does not work as expected I guess). I assume something went wrong during the generation of the graph and pygraphviz cannot convert it into a valid output.

I suggest that you run a debugger and set a breakpoint exactly at that line (1335) or just print out the content of `error` (which requires an extra line of code in pygraphviz). Alternatively you can print self.graph.string() to get the content of the graph.

If you can provide a minimal example to reproduce the bug I can help to track down the bug.

**Comment by guilhermecgs** [comment] 2016-10-19 16:48
@aleneum , I will do the additional debugging and inform you

btw, I can change the state name and make it work. So, it is not something critical...  It is just a curiosity...

**Comment by aleneum** [comment] 2016-10-22 07:57
@guilhermecgs, that would be nice since it sounds like a really strange side effect (which makes me curious as well :) ). Afaik, there are no reserved key words for states. Maybe some dot/Graphviz naming collision but thats just random guessing.

**Comment by aleneum** [comment] 2016-11-20 18:42
Hi @guilhermecgs,

were you able to do some debugging? I experienced IOErrors if I tried to save graphs to directories or file locations with wrong permissions.

**Comment by aleneum** [comment] 2016-12-01 13:49
I close this for now due to lack of information. It sounds like a side effect though. Feel free to reopen if you have further cues to investigate.

**Closed by aleneum** 2016-12-01 13:49 UTC
